### PR TITLE
Add the new onDateSelect event

### PR DESCRIPTION
**Pull request by dimko**
It can be implemented using `click` event. But will require to duplicate the logic of detecting inactive days. Wdyt?

### CODE REVIEW

**Comment by dimko** [comment]
@mikegioia would like to hear your thoughts on this.

**Comment by kylestetz** [comment]
Thanks for the PR @dimko! I understand the convenience of not having to deal with the inactive day logic, but I don't like that this introduces two events with overlapping functionality; if this option is turned on, both `click` and `onDateSelect` will fire for a given click event. Additionally, some work happens in the DOM between the two events, causing them to represent two slightly different points in time.

Our main goal in maintaining the plugin is to support a small set of features that overlap as little as possible because this makes them much easier to maintain, refactor, and document for everyone. For those reasons I'm leaning towards this not being a good fit— @mikegioia what do you think?

**Comment by mikegioia** [comment]
Yea I second what Kyle said. This seems duplicative.

**Comment by dimko** [comment]
OK, thanks for the feedback! Closing.

**Pull request closed without merging**
