### PR TITLE
Style and event handling cleanup + a few bug fixes

### PR DESCRIPTION
**Pull request by mikegioia**
The main update here is a cleanup of the codebase according to [Douglas Crockford's style guide](http://javascript.crockford.com/code.html). Additional updates are listed below but they we're mainly around cleaning up the event handling for change events.

1. There were inconsistencies in some of the duplicate functions not firing the same events or having the same logic. For example `forwardActionWithContext` triggers a `nextMonth` and `nextInterval` event but `forward` doesn't.
2. The events `nextInterval` and `previousInterval` weren't documented anywhere and weren't used consistently.
3. Cleaned up some of the logic around `lengthOfTime`. The original merge left in some extra verbosity that could be simplified.
4. Remove the Underscore.js dependency. The last remaining use (other than `_.template`) was `_.reduce` to count the `numberOfRows` in `render()`. This was replaced with a loop instead.
5. All event triggering is now handled in `triggerEvents` which takes the old interval and the new interval, compares them, and figures out which events like 'monthChange' or 'nextYear' to fire. The original behavior was left but see #225 for more information on this.
6. Constraint checking was handled by looking for an 'inactive' class on the respective button. For example, calling `back()` would check if the `previousButton` DOM node had a class "inactive" on it in determining if going back was allowed. This could fail in the event there was no previousButton in the DOM. Instead, an object containing this constraint information is saved internally and checked against.
7. The 'inactive' class was hardcoded in many places and that was removed to use the config variable.
8. A hard 80-char width was imposed on the entire file except for 1 or 2 locations
9. Added a lot more comments to various places. Cleaned up wrong or old comments.
10. Added a `today` action to the events API. There was none before but there was an internal `todayAction` that is used.

##### ToDo:

 - [x] Move example to demo folder, and tests to test folder
 - [x] Clean up demo
 - [x] Clean up Gruntfile
 - [x] Clean up Readme
 - [x] Move Changelog out to a separate file
 - [x] Clean up tests
 - [x] Run through all tests, audit tests, and make sure any new tests that are needed are added

##### Questions for @kylestetz 

- [x] I removed the "Powered by Punkave" image from the bottom of the Readme. Is that ok to do?

### CODE REVIEW

**Comment by mikegioia** [comment]
This is ready for review.

**Comment by kylestetz** [comment]
:clap: This all looks great. I ran the test page and everything worked except for the very last example, which tests the `ignoreInactiveDaysInSelection` option.

**Comment by mikegioia** [comment]
Ok I'll check that one out later tonight. Also, I know the filesize of `src/clndr.js` is higher but that's only because of the spaces and additional comments. The minified version is actually 4kb smaller I think :+1:

**Comment by mikegioia** [comment]
@kylestetz I don't see any problem with final test (ignoreInactiveDaysInSelection). December 13th and on, plus October 23 and before are all preventing from turning purple for me. Only the valid date range highlights. I'm on chrome in Ubuntu (fyi).

**Comment by kylestetz** [comment]
Hey! You're right. I was doing the wrong thing to test it.

Totally fantastic, thank you so much for tackling this. I am going to mash the merge button and take the conversation over to #225.

**Comment by mikegioia** [comment]
Yea of course. I just realized I never bumped the version anywhere.

**Pull request merged**
