### PR TITLE
allow previousMonth and nextMonth in templates

### PR DESCRIPTION
**Pull request by jhmegorei**
I needed the strings for the previous and next month in the template, so I added them. Maybe you like the change.

Best regards

Johannes

### CODE REVIEW

**Comment by kylestetz** [comment]
Love it, as I'm sure a lot of people will. Thanks!

**Comment by jhmegorei** [comment]
I hope this was not premature though :-/ I had trouble updating the fields, when changing the current month. (e.g. active month = march, previous month = february, next month = april -> click on april, prev and next month still show feb/april). I wasn't yet able to fix this, as I was out of the country for a while.

**Comment by kylestetz** [comment]
Your usage of moment wasn't quite right, but I'm fixing it up right now. It should be:

```javascript
previousMonth: this.month.clone().subtract(1, 'month').format('MMMM'),
nextMonth: this.month.clone().add(1, 'month').format('MMMM')
```

The issue was that calling `month(-1)` and `month(+1)` sets the month (in absolute terms) to December and February, respectively.

**Comment by jhmegorei** [comment]
Ah, I see. Should have read the Moment.js docu better. Thank you for pointing it out and fixing it :)

**Comment by kylestetz** [comment]
No problem! Just published this in v1.2.8. Thanks again.

**Pull request merged**
