### PR TITLE
Update CLNDR version in Pages branch

### PR DESCRIPTION
**Pull request by long-lazuli**

### CODE REVIEW

**Comment by mikegioia** [comment]
@long-lazuli I don't understand this PR, why is there a version bump?

**Comment by long-lazuli** [comment]
The purpose of this PR is indeed to reflects the current state of the project on the gh-pages branch.

**Comment by mikegioia** [comment]
This will probably need to get a newer copy of the library

**Comment by long-lazuli** [comment]
I think we should close this PR.

**Comment by long-lazuli** [comment]
You should make gh-pages branch appart from the rest of dev flow.
On my recents projects, I use the [`gh-pages` npm package](https://www.npmjs.com/package/gh-pages) and deploy only the public/ directory onto gh-pages branch.

That could help !

**Pull request closed without merging**
